import { useEffect, useId, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TextareaHTMLAttributes } from "react";
import { AlertCircle, Inbox, LoaderCircle } from "lucide-react";
import { priorityLabels, roleLabels, statusLabels } from "../constants/labels";

export function Button({ className = "", variant = "primary", loading, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "danger" | "ghost"; loading?: boolean }) {
  return <button className={`button button-${variant} ${className}`} disabled={props.disabled || loading} {...props}>{loading && <LoaderCircle size={17} className="spinner" aria-hidden="true" />}<span>{children}</span></button>;
}
export function Input({ label, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) { const generatedId = useId(); const id = props.id ?? props.name ?? generatedId; return <div className="field"><label htmlFor={id}>{label}</label><input id={id} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} {...props} />{error && <small id={`${id}-error`} className="field-error">{error}</small>}</div>; }
export function Textarea({ label, error, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label: string; error?: string }) { const generatedId = useId(); const id = props.id ?? props.name ?? generatedId; return <div className="field"><label htmlFor={id}>{label}</label><textarea id={id} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} {...props} />{error && <small id={`${id}-error`} className="field-error">{error}</small>}</div>; }
export function Select({ label, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label: string; children: ReactNode }) { const generatedId = useId(); const id = props.id ?? props.name ?? generatedId; return <div className="field"><label htmlFor={id}>{label}</label><select id={id} {...props}>{children}</select></div>; }
export function Card({ children, className = "", ...props }: HTMLAttributes<HTMLElement> & { children: ReactNode }) { return <section className={`card ${className}`} {...props}>{children}</section>; }
export function StatusBadge({ status }: { status: string }) { return <span className={`badge status-${status.toLowerCase()}`}><span aria-hidden="true" className="badge-dot" />{statusLabels[status] ?? status}</span>; }
export function PriorityBadge({ priority }: { priority: string }) { return <span className={`badge priority-${priority.toLowerCase()}`}><span aria-hidden="true" className="badge-dot" />{priorityLabels[priority] ?? priority}</span>; }
export function RoleBadge({ role }: { role: string }) { return <span className="badge badge-neutral">{roleLabels[role] ?? role}</span>; }
export function LoadingState({ label = "Daten werden geladen …" }: { label?: string }) { return <div className="state" role="status"><LoaderCircle className="spinner" /><p>{label}</p></div>; }
export function EmptyState({ title = "Keine Einträge vorhanden", description = "Für die aktuelle Auswahl wurden keine Daten gefunden." }: { title?: string; description?: string }) { return <div className="state"><Inbox /><strong>{title}</strong><p>{description}</p></div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="state error-state" role="alert"><AlertCircle /><strong>Daten konnten nicht geladen werden</strong><p>{message}</p>{retry && <Button variant="secondary" onClick={retry}>Erneut versuchen</Button>}</div>; }
export function PageTitle({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="page-title"><div><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }

export function ConfirmDialog({ open, title, description, confirmLabel = "Bestätigen", danger = false, loading = false, onConfirm, onCancel }: { open: boolean; title: string; description: string; confirmLabel?: string; danger?: boolean; loading?: boolean; onConfirm: () => void; onCancel: () => void }) {
  useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") onCancel(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [open, onCancel]);
  if (!open) return null;
  return <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onCancel(); }}><div className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" aria-describedby="confirm-description"><h2 id="confirm-title">{title}</h2><p id="confirm-description">{description}</p><div className="form-actions"><Button variant="ghost" onClick={onCancel} disabled={loading}>Abbrechen</Button><Button variant={danger ? "danger" : "primary"} onClick={onConfirm} loading={loading} autoFocus>{confirmLabel}</Button></div></div></div>;
}
