import express from "express";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import { env } from "./config/env.js";
import { mountSwagger } from "./config/swagger.js";
import { errorHandler, notFound } from "./middleware/errorHandler.js";
import { authRouter } from "./routes/auth.js";
import { ticketRouter } from "./routes/tickets.js";
import { attachmentRouter } from "./routes/attachments.js";
import { userRouter } from "./routes/users.js";
import { categoryRouter, slaRouter, tagRouter, teamRouter } from "./routes/resources.js";
import { dashboardRouter } from "./routes/dashboard.js";
import { notificationRouter } from "./routes/notifications.js";
import { knowledgeBaseRouter } from "./routes/knowledgeBase.js";
import { auditRouter, reportRouter } from "./routes/admin.js";

export const app = express();
app.disable("x-powered-by");
app.set("trust proxy", 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: "same-site" } }));
app.use(cors({ origin: env.FRONTEND_URL, credentials: false, methods: ["GET", "POST", "PUT", "PATCH", "DELETE"] }));
app.use(express.json({ limit: "1mb" }));
app.use(express.urlencoded({ extended: false, limit: "1mb" }));
app.use("/api/v1/auth/login", rateLimit({ windowMs: 15 * 60_000, limit: 10, skipSuccessfulRequests: true, standardHeaders: "draft-7", legacyHeaders: false, message: { success: false, message: "Zu viele Anmeldeversuche. Bitte versuchen Sie es später erneut.", code: "RATE_LIMITED" } }));
app.use("/api/v1", rateLimit({ windowMs: 15 * 60_000, limit: 500, standardHeaders: "draft-7", legacyHeaders: false }));
app.get("/health", (_request, response) => response.json({ success: true, data: { status: "bereit", application: "JAM IT HelpDesk" } }));
mountSwagger(app);
app.use("/api/v1/auth", authRouter);
app.use("/api/v1/tickets", ticketRouter);
app.use("/api/v1/attachments", attachmentRouter);
app.use("/api/v1/users", userRouter);
app.use("/api/v1/categories", categoryRouter);
app.use("/api/v1/teams", teamRouter);
app.use("/api/v1/tags", tagRouter);
app.use("/api/v1/sla-policies", slaRouter);
app.use("/api/v1/dashboard", dashboardRouter);
app.use("/api/v1/notifications", notificationRouter);
app.use("/api/v1/knowledge-base", knowledgeBaseRouter);
app.use("/api/v1/audit-logs", auditRouter);
app.use("/api/v1/reports", reportRouter);
app.use(notFound);
app.use(errorHandler);
