import { useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Link, Navigate, useNavigate, useSearchParams } from "react-router-dom";
import { CheckCircle2, LockKeyhole, ShieldCheck, TicketCheck } from "lucide-react";
import { api, apiErrorMessage } from "../api/client";
import { appConfig } from "../config/brand";
import { useAuth } from "../contexts/AuthContext";
import { Button, Input } from "../components/ui";

function AuthShell({ children }: { children: ReactNode }) { return <div className="auth-shell"><section className="auth-brand"><div className="brand-mark"><div className="brand-icon">JI</div><div><strong>JAM IT Dienstleistungen</strong><div>Support- und Ticketmanagement</div></div></div><div><h1>IT-Support, der transparent und verlässlich bleibt.</h1><p>Erfassen Sie Supportanfragen sicher, verfolgen Sie den Bearbeitungsstand und bleiben Sie direkt mit unserem Serviceteam in Kontakt.</p><div className="auth-features"><div className="auth-feature"><TicketCheck size={20} />Übersichtliche Ticketverfolgung</div><div className="auth-feature"><ShieldCheck size={20} />Sichere Kommunikation und Anhänge</div><div className="auth-feature"><CheckCircle2 size={20} />Verbindliche Bearbeitungsziele</div></div></div><small>© {new Date().getFullYear()} {appConfig.companyName}</small></section><section className="auth-panel">{children}</section></div>; }

const loginSchema = z.object({ email: z.string().email("Bitte geben Sie eine gültige E-Mail-Adresse ein."), password: z.string().min(1, "Bitte geben Sie Ihr Passwort ein.") });
type LoginInput = z.infer<typeof loginSchema>;
export function LoginPage() {
  const { user, login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState("");
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<LoginInput>({ resolver: zodResolver(loginSchema), defaultValues: { email: "", password: "" } });
  if (user) return <Navigate to="/dashboard" replace />;
  const submit = async (input: LoginInput) => { setError(""); try { await login(input.email, input.password); navigate("/dashboard"); } catch (reason) { setError(apiErrorMessage(reason)); } };
  return <AuthShell><div className="auth-card"><LockKeyhole size={30} aria-hidden="true" /><h2>Willkommen zurück</h2><p>Melden Sie sich bei JAM IT HelpDesk an.</p><form className="auth-form" onSubmit={handleSubmit(submit)} noValidate>{error && <div className="form-alert" role="alert">{error}</div>}<Input label="E-Mail-Adresse" type="email" autoComplete="email" {...register("email")} error={errors.email?.message} /><Input label="Passwort" type="password" autoComplete="current-password" {...register("password")} error={errors.password?.message} /><Button type="submit" loading={isSubmitting}>Anmelden</Button></form><div className="auth-links"><Link className="text-link" to="/passwort-vergessen">Passwort vergessen?</Link><Link className="text-link" to="/registrieren">Konto erstellen</Link></div><div className="warning-box" style={{ marginTop: "1.5rem" }}><ShieldCheck size={18} /><span>Demo: kunde@jam-it.local / Kunde123!</span></div></div></AuthShell>;
}

const registrationSchema = z.object({ firstName: z.string().min(2, "Bitte geben Sie Ihren Vornamen ein."), lastName: z.string().min(2, "Bitte geben Sie Ihren Nachnamen ein."), email: z.string().email("Bitte geben Sie eine gültige E-Mail-Adresse ein."), company: z.string().optional(), password: z.string().min(10, "Mindestens 10 Zeichen erforderlich.").regex(/[A-Z]/, "Ein Großbuchstabe ist erforderlich.").regex(/[a-z]/, "Ein Kleinbuchstabe ist erforderlich.").regex(/[0-9]/, "Eine Zahl ist erforderlich.").regex(/[^A-Za-z0-9]/, "Ein Sonderzeichen ist erforderlich."), confirmPassword: z.string() }).refine((data) => data.password === data.confirmPassword, { path: ["confirmPassword"], message: "Die Passwörter stimmen nicht überein." });
type RegistrationInput = z.infer<typeof registrationSchema>;
export function RegisterPage() {
  const navigate = useNavigate(); const [error, setError] = useState(""); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<RegistrationInput>({ resolver: zodResolver(registrationSchema) });
  const submit = async ({ confirmPassword: _confirmPassword, ...input }: RegistrationInput) => { try { await api.post("/auth/register", input); navigate("/anmelden", { replace: true }); } catch (reason) { setError(apiErrorMessage(reason)); } };
  return <AuthShell><div className="auth-card"><h2>Konto erstellen</h2><p>Registrieren Sie sich für das Kundenportal.</p><form className="auth-form" onSubmit={handleSubmit(submit)}>{error && <div className="form-alert" role="alert">{error}</div>}<div className="form-grid"><Input label="Vorname" {...register("firstName")} error={errors.firstName?.message} /><Input label="Nachname" {...register("lastName")} error={errors.lastName?.message} /><div className="form-span"><Input label="E-Mail-Adresse" type="email" {...register("email")} error={errors.email?.message} /></div><div className="form-span"><Input label="Unternehmen (optional)" {...register("company")} /></div><Input label="Passwort" type="password" {...register("password")} error={errors.password?.message} /><Input label="Passwort wiederholen" type="password" {...register("confirmPassword")} error={errors.confirmPassword?.message} /></div><Button type="submit" loading={isSubmitting}>Registrieren</Button></form><div className="auth-links"><Link className="text-link" to="/anmelden">Zur Anmeldung</Link></div></div></AuthShell>;
}

export function ForgotPasswordPage() {
  const [message, setMessage] = useState(""); const [developmentToken, setDevelopmentToken] = useState(""); const [error, setError] = useState(""); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<{ email: string }>({ resolver: zodResolver(z.object({ email: z.string().email("Bitte geben Sie eine gültige E-Mail-Adresse ein.") })) });
  const submit = async (input: { email: string }) => { try { const { data } = await api.post<{ message: string; data?: { developmentResetToken?: string } }>("/auth/forgot-password", input); setMessage(data.message); setDevelopmentToken(data.data?.developmentResetToken ?? ""); } catch (reason) { setError(apiErrorMessage(reason)); } };
  return <AuthShell><div className="auth-card"><h2>Passwort vergessen</h2><p>Wir senden Ihnen einen zeitlich begrenzten Link.</p>{message ? <div><div className="warning-box"><CheckCircle2 size={18} />{message}</div>{developmentToken && <div className="auth-links"><Link className="text-link" to={`/passwort-zuruecksetzen?token=${encodeURIComponent(developmentToken)}`}>Entwicklungslink öffnen</Link></div>}</div> : <form className="auth-form" onSubmit={handleSubmit(submit)}>{error && <div className="form-alert">{error}</div>}<Input label="E-Mail-Adresse" type="email" {...register("email")} error={errors.email?.message} /><Button type="submit" loading={isSubmitting}>Link anfordern</Button></form>}<div className="auth-links"><Link className="text-link" to="/anmelden">Zur Anmeldung</Link></div></div></AuthShell>;
}

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const [error, setError] = useState(""); const schema = z.object({ password: z.string().min(10, "Mindestens 10 Zeichen erforderlich."), confirmPassword: z.string() }).refine((data) => data.password === data.confirmPassword, { path: ["confirmPassword"], message: "Die Passwörter stimmen nicht überein." }); type Input = z.infer<typeof schema>; const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Input>({ resolver: zodResolver(schema) });
  const submit = async (input: Input) => { try { await api.post("/auth/reset-password", { token: params.get("token"), password: input.password }); navigate("/anmelden"); } catch (reason) { setError(apiErrorMessage(reason)); } };
  return <AuthShell><div className="auth-card"><h2>Neues Passwort</h2><p>Legen Sie ein sicheres Passwort für Ihr Konto fest.</p><form className="auth-form" onSubmit={handleSubmit(submit)}>{error && <div className="form-alert">{error}</div>}<Input label="Neues Passwort" type="password" {...register("password")} error={errors.password?.message} /><Input label="Passwort wiederholen" type="password" {...register("confirmPassword")} error={errors.confirmPassword?.message} /><Button type="submit" loading={isSubmitting}>Passwort speichern</Button></form></div></AuthShell>;
}
