import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AlertTriangle, MapPinOff } from "lucide-react";
import { api, apiErrorMessage } from "../api/client";
import { Button, Card, Input, PageTitle } from "../components/ui";
import { useAuth } from "../contexts/AuthContext";

export function UnauthorizedPage() { return <div className="state" style={{ minHeight: "70vh" }}><AlertTriangle size={42} /><h1>Nicht berechtigt</h1><p>Sie sind nicht berechtigt, diese Seite oder Aktion aufzurufen.</p><Link to="/dashboard"><Button>Zum Dashboard</Button></Link></div>; }
export function NotFoundPage() { return <div className="state" style={{ minHeight: "70vh" }}><MapPinOff size={42} /><h1>Seite nicht gefunden</h1><p>Die angeforderte Seite existiert nicht oder wurde verschoben.</p><Link to="/dashboard"><Button>Zum Dashboard</Button></Link></div>; }
export function ProfilePage() {
  const { user, refresh, logout } = useAuth(); const navigate = useNavigate(); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const [profile, setProfile] = useState({ firstName: user?.firstName ?? "", lastName: user?.lastName ?? "", phone: user?.phone ?? "", company: user?.company ?? "", department: user?.department ?? "", position: user?.position ?? "" });
  const [passwords, setPasswords] = useState({ currentPassword: "", newPassword: "", confirmPassword: "" });
  if (!user) return null;
  const saveProfile = async () => { setSaving(true); setMessage(""); try { const response = await api.patch("/auth/profile", profile); setMessage(response.data.message); await refresh(); } catch (error) { setMessage(apiErrorMessage(error)); } finally { setSaving(false); } };
  const changePassword = async () => { if (passwords.newPassword !== passwords.confirmPassword) return setMessage("Die neuen Passwörter stimmen nicht überein."); setSaving(true); setMessage(""); try { await api.post("/auth/change-password", { currentPassword: passwords.currentPassword, newPassword: passwords.newPassword }); await logout(); navigate("/anmelden"); } catch (error) { setMessage(apiErrorMessage(error)); } finally { setSaving(false); } };
  return <><PageTitle title="Profil" description="Kontaktdaten und Kontosicherheit verwalten." />{message && <div className="warning-box" style={{ marginBottom: "1rem" }}>{message}</div>}<div className="dashboard-grid"><Card><h2>Persönliche Daten</h2><div className="form-grid"><Input label="Vorname" value={profile.firstName} onChange={(event) => setProfile({ ...profile, firstName: event.target.value })} /><Input label="Nachname" value={profile.lastName} onChange={(event) => setProfile({ ...profile, lastName: event.target.value })} /><Input label="Telefon" value={profile.phone} onChange={(event) => setProfile({ ...profile, phone: event.target.value })} /><Input label="Firma" value={profile.company} onChange={(event) => setProfile({ ...profile, company: event.target.value })} /><Input label="Abteilung" value={profile.department} onChange={(event) => setProfile({ ...profile, department: event.target.value })} /><Input label="Position" value={profile.position} onChange={(event) => setProfile({ ...profile, position: event.target.value })} /></div><div className="form-actions"><Button loading={saving} onClick={() => void saveProfile()}>Profil speichern</Button></div></Card><Card><h2>Passwort ändern</h2><div className="auth-form"><Input label="Aktuelles Passwort" type="password" autoComplete="current-password" value={passwords.currentPassword} onChange={(event) => setPasswords({ ...passwords, currentPassword: event.target.value })} /><Input label="Neues Passwort" type="password" autoComplete="new-password" value={passwords.newPassword} onChange={(event) => setPasswords({ ...passwords, newPassword: event.target.value })} /><Input label="Neues Passwort wiederholen" type="password" autoComplete="new-password" value={passwords.confirmPassword} onChange={(event) => setPasswords({ ...passwords, confirmPassword: event.target.value })} /><Button disabled={passwords.newPassword.length < 10 || !passwords.currentPassword} loading={saving} onClick={() => void changePassword()}>Passwort ändern</Button></div></Card></div></>;
}
